language: rust
rust: nightly
cache: cargo


before_script:
	- sudo apt-get install -y lgfortran
	- sudo apt-get install -y lopenblas
	- export PATH="$PATH:$HOME/.cargo/bin"
script:
- cargo build --release
- cargo test --release --features=logs