language: rust
rust: nightly
cache: cargo

before_script:
- sudo apt-get install libopenblas-dev
- sudo apt-get install -y gfortran
- export PATH="$PATH:$HOME/.cargo/bin"
script:
- cargo build --release
- cargo test --release --features=logs