language: rust
rust: nightly
cache: cargo

before_install:
  - sudo apt-get install -y gfortran
	- sudo apt-get install openblas-dev
before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
script:
- cargo build --release
- cargo test --release --features=logs